[workspace]
resolver = "2"
members = [
    "subprojects/nx-cpu",
    "subprojects/nx-svc",
    "subprojects/nx-sync",
    "subprojects/nx-thread",
    "subprojects/nx-time",
]


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
