[package]
name = "nx-cpu"
version = "0.1.0"
edition = "2024"

[lib]
name = "nx_cpu"
crate-type = ["rlib", "staticlib"]
test = false
doctest = false
bench = false

[dependencies]
panic-abort = "0.3.2"
panic-halt = "1.0.0"
